---

name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
      -
        uses: ruby/setup-ruby@v1
      -
        name: Build the Docker image
        run: rake container:build
...
